"""
Export a report's Markdown content into downloadable formats (FR-15).

Deliberately implements a small, dependency-light Markdown subset (H1-H3,
bullet lists, paragraphs) rather than pulling in a full HTML+CSS rendering
pipeline - reports generated by the agent are structured but not visually
complex, so this covers the real cases without a heavy toolchain.
"""
from __future__ import annotations

import io


def _parse_lines(content_md: str) -> list[tuple[str, str]]:
    """Return a list of (block_type, text) tuples: heading1/2/3, bullet, para, blank."""
    blocks = []
    for raw_line in content_md.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            blocks.append(("blank", ""))
        elif line.startswith("### "):
            blocks.append(("h3", line[4:].strip()))
        elif line.startswith("## "):
            blocks.append(("h2", line[3:].strip()))
        elif line.startswith("# "):
            blocks.append(("h1", line[2:].strip()))
        elif line.lstrip().startswith(("- ", "* ")):
            blocks.append(("bullet", line.lstrip()[2:].strip()))
        else:
            blocks.append(("para", line.strip()))
    return blocks


def export_markdown_bytes(content_md: str) -> bytes:
    return content_md.encode("utf-8")


def export_docx_bytes(content_md: str, title: str) -> bytes:
    from docx import Document as DocxDocument
    from docx.shared import Pt

    doc = DocxDocument()
    doc.add_heading(title, level=0)

    for block_type, text in _parse_lines(content_md):
        if block_type == "blank":
            continue
        elif block_type == "h1":
            doc.add_heading(text, level=1)
        elif block_type == "h2":
            doc.add_heading(text, level=2)
        elif block_type == "h3":
            doc.add_heading(text, level=3)
        elif block_type == "bullet":
            doc.add_paragraph(text, style="List Bullet")
        else:
            if text:
                doc.add_paragraph(text)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_pdf_bytes(content_md: str, title: str) -> bytes:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, ListFlowable, ListItem

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        leftMargin=1 * inch, rightMargin=1 * inch, topMargin=1 * inch, bottomMargin=1 * inch,
    )
    styles = getSampleStyleSheet()
    story = [Paragraph(_escape(title), styles["Title"]), Spacer(1, 16)]

    bullet_buffer: list[str] = []

    def flush_bullets():
        nonlocal bullet_buffer
        if bullet_buffer:
            story.append(
                ListFlowable(
                    [ListItem(Paragraph(_escape(b), styles["Normal"])) for b in bullet_buffer],
                    bulletType="bullet",
                )
            )
            bullet_buffer = []

    for block_type, text in _parse_lines(content_md):
        if block_type == "bullet":
            bullet_buffer.append(text)
            continue
        flush_bullets()
        if block_type == "blank":
            story.append(Spacer(1, 6))
        elif block_type == "h1":
            story.append(Paragraph(_escape(text), styles["Heading1"]))
        elif block_type == "h2":
            story.append(Paragraph(_escape(text), styles["Heading2"]))
        elif block_type == "h3":
            story.append(Paragraph(_escape(text), styles["Heading3"]))
        elif text:
            story.append(Paragraph(_escape(text), styles["Normal"]))
    flush_bullets()

    doc.build(story)
    return buf.getvalue()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
